/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PrivacyPolicyImport } from './routes/privacy-policy'
import { Route as IndexImport } from './routes/index'
import { Route as ServicesZkDevelopmentImport } from './routes/services/zk-development'
import { Route as ServicesWalletDevelopmentImport } from './routes/services/wallet-development'
import { Route as ServicesSmartContractDevelopmentImport } from './routes/services/smart-contract-development'
import { Route as ServicesRwaImport } from './routes/services/rwa'
import { Route as ServicesPredictionMarketDevelopmentImport } from './routes/services/prediction-market-development'
import { Route as ServicesLaunchpadImport } from './routes/services/launchpad'
import { Route as ServicesGamefiDevelopmentImport } from './routes/services/gamefi-development'
import { Route as ServicesDefiSecurityAuditImport } from './routes/services/defi-security-audit'
import { Route as ServicesDefiDevelopmentImport } from './routes/services/defi-development'
import { Route as ServicesDaoDevelopmentImport } from './routes/services/dao-development'

// Create/Update Routes

const PrivacyPolicyRoute = PrivacyPolicyImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/privacy-policy.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const ServicesZkDevelopmentRoute = ServicesZkDevelopmentImport.update({
  id: '/services/zk-development',
  path: '/services/zk-development',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/services/zk-development.lazy').then((d) => d.Route),
)

const ServicesWalletDevelopmentRoute = ServicesWalletDevelopmentImport.update({
  id: '/services/wallet-development',
  path: '/services/wallet-development',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/services/wallet-development.lazy').then((d) => d.Route),
)

const ServicesSmartContractDevelopmentRoute =
  ServicesSmartContractDevelopmentImport.update({
    id: '/services/smart-contract-development',
    path: '/services/smart-contract-development',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/services/smart-contract-development.lazy').then(
      (d) => d.Route,
    ),
  )

const ServicesRwaRoute = ServicesRwaImport.update({
  id: '/services/rwa',
  path: '/services/rwa',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/services/rwa.lazy').then((d) => d.Route))

const ServicesPredictionMarketDevelopmentRoute =
  ServicesPredictionMarketDevelopmentImport.update({
    id: '/services/prediction-market-development',
    path: '/services/prediction-market-development',
    getParentRoute: () => rootRoute,
  } as any).lazy(() =>
    import('./routes/services/prediction-market-development.lazy').then(
      (d) => d.Route,
    ),
  )

const ServicesLaunchpadRoute = ServicesLaunchpadImport.update({
  id: '/services/launchpad',
  path: '/services/launchpad',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/services/launchpad.lazy').then((d) => d.Route),
)

const ServicesGamefiDevelopmentRoute = ServicesGamefiDevelopmentImport.update({
  id: '/services/gamefi-development',
  path: '/services/gamefi-development',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/services/gamefi-development.lazy').then((d) => d.Route),
)

const ServicesDefiSecurityAuditRoute = ServicesDefiSecurityAuditImport.update({
  id: '/services/defi-security-audit',
  path: '/services/defi-security-audit',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/services/defi-security-audit.lazy').then((d) => d.Route),
)

const ServicesDefiDevelopmentRoute = ServicesDefiDevelopmentImport.update({
  id: '/services/defi-development',
  path: '/services/defi-development',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/services/defi-development.lazy').then((d) => d.Route),
)

const ServicesDaoDevelopmentRoute = ServicesDaoDevelopmentImport.update({
  id: '/services/dao-development',
  path: '/services/dao-development',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/services/dao-development.lazy').then((d) => d.Route),
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyImport
      parentRoute: typeof rootRoute
    }
    '/services/dao-development': {
      id: '/services/dao-development'
      path: '/services/dao-development'
      fullPath: '/services/dao-development'
      preLoaderRoute: typeof ServicesDaoDevelopmentImport
      parentRoute: typeof rootRoute
    }
    '/services/defi-development': {
      id: '/services/defi-development'
      path: '/services/defi-development'
      fullPath: '/services/defi-development'
      preLoaderRoute: typeof ServicesDefiDevelopmentImport
      parentRoute: typeof rootRoute
    }
    '/services/defi-security-audit': {
      id: '/services/defi-security-audit'
      path: '/services/defi-security-audit'
      fullPath: '/services/defi-security-audit'
      preLoaderRoute: typeof ServicesDefiSecurityAuditImport
      parentRoute: typeof rootRoute
    }
    '/services/gamefi-development': {
      id: '/services/gamefi-development'
      path: '/services/gamefi-development'
      fullPath: '/services/gamefi-development'
      preLoaderRoute: typeof ServicesGamefiDevelopmentImport
      parentRoute: typeof rootRoute
    }
    '/services/launchpad': {
      id: '/services/launchpad'
      path: '/services/launchpad'
      fullPath: '/services/launchpad'
      preLoaderRoute: typeof ServicesLaunchpadImport
      parentRoute: typeof rootRoute
    }
    '/services/prediction-market-development': {
      id: '/services/prediction-market-development'
      path: '/services/prediction-market-development'
      fullPath: '/services/prediction-market-development'
      preLoaderRoute: typeof ServicesPredictionMarketDevelopmentImport
      parentRoute: typeof rootRoute
    }
    '/services/rwa': {
      id: '/services/rwa'
      path: '/services/rwa'
      fullPath: '/services/rwa'
      preLoaderRoute: typeof ServicesRwaImport
      parentRoute: typeof rootRoute
    }
    '/services/smart-contract-development': {
      id: '/services/smart-contract-development'
      path: '/services/smart-contract-development'
      fullPath: '/services/smart-contract-development'
      preLoaderRoute: typeof ServicesSmartContractDevelopmentImport
      parentRoute: typeof rootRoute
    }
    '/services/wallet-development': {
      id: '/services/wallet-development'
      path: '/services/wallet-development'
      fullPath: '/services/wallet-development'
      preLoaderRoute: typeof ServicesWalletDevelopmentImport
      parentRoute: typeof rootRoute
    }
    '/services/zk-development': {
      id: '/services/zk-development'
      path: '/services/zk-development'
      fullPath: '/services/zk-development'
      preLoaderRoute: typeof ServicesZkDevelopmentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services/dao-development': typeof ServicesDaoDevelopmentRoute
  '/services/defi-development': typeof ServicesDefiDevelopmentRoute
  '/services/defi-security-audit': typeof ServicesDefiSecurityAuditRoute
  '/services/gamefi-development': typeof ServicesGamefiDevelopmentRoute
  '/services/launchpad': typeof ServicesLaunchpadRoute
  '/services/prediction-market-development': typeof ServicesPredictionMarketDevelopmentRoute
  '/services/rwa': typeof ServicesRwaRoute
  '/services/smart-contract-development': typeof ServicesSmartContractDevelopmentRoute
  '/services/wallet-development': typeof ServicesWalletDevelopmentRoute
  '/services/zk-development': typeof ServicesZkDevelopmentRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services/dao-development': typeof ServicesDaoDevelopmentRoute
  '/services/defi-development': typeof ServicesDefiDevelopmentRoute
  '/services/defi-security-audit': typeof ServicesDefiSecurityAuditRoute
  '/services/gamefi-development': typeof ServicesGamefiDevelopmentRoute
  '/services/launchpad': typeof ServicesLaunchpadRoute
  '/services/prediction-market-development': typeof ServicesPredictionMarketDevelopmentRoute
  '/services/rwa': typeof ServicesRwaRoute
  '/services/smart-contract-development': typeof ServicesSmartContractDevelopmentRoute
  '/services/wallet-development': typeof ServicesWalletDevelopmentRoute
  '/services/zk-development': typeof ServicesZkDevelopmentRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/services/dao-development': typeof ServicesDaoDevelopmentRoute
  '/services/defi-development': typeof ServicesDefiDevelopmentRoute
  '/services/defi-security-audit': typeof ServicesDefiSecurityAuditRoute
  '/services/gamefi-development': typeof ServicesGamefiDevelopmentRoute
  '/services/launchpad': typeof ServicesLaunchpadRoute
  '/services/prediction-market-development': typeof ServicesPredictionMarketDevelopmentRoute
  '/services/rwa': typeof ServicesRwaRoute
  '/services/smart-contract-development': typeof ServicesSmartContractDevelopmentRoute
  '/services/wallet-development': typeof ServicesWalletDevelopmentRoute
  '/services/zk-development': typeof ServicesZkDevelopmentRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy-policy'
    | '/services/dao-development'
    | '/services/defi-development'
    | '/services/defi-security-audit'
    | '/services/gamefi-development'
    | '/services/launchpad'
    | '/services/prediction-market-development'
    | '/services/rwa'
    | '/services/smart-contract-development'
    | '/services/wallet-development'
    | '/services/zk-development'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy-policy'
    | '/services/dao-development'
    | '/services/defi-development'
    | '/services/defi-security-audit'
    | '/services/gamefi-development'
    | '/services/launchpad'
    | '/services/prediction-market-development'
    | '/services/rwa'
    | '/services/smart-contract-development'
    | '/services/wallet-development'
    | '/services/zk-development'
  id:
    | '__root__'
    | '/'
    | '/privacy-policy'
    | '/services/dao-development'
    | '/services/defi-development'
    | '/services/defi-security-audit'
    | '/services/gamefi-development'
    | '/services/launchpad'
    | '/services/prediction-market-development'
    | '/services/rwa'
    | '/services/smart-contract-development'
    | '/services/wallet-development'
    | '/services/zk-development'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServicesDaoDevelopmentRoute: typeof ServicesDaoDevelopmentRoute
  ServicesDefiDevelopmentRoute: typeof ServicesDefiDevelopmentRoute
  ServicesDefiSecurityAuditRoute: typeof ServicesDefiSecurityAuditRoute
  ServicesGamefiDevelopmentRoute: typeof ServicesGamefiDevelopmentRoute
  ServicesLaunchpadRoute: typeof ServicesLaunchpadRoute
  ServicesPredictionMarketDevelopmentRoute: typeof ServicesPredictionMarketDevelopmentRoute
  ServicesRwaRoute: typeof ServicesRwaRoute
  ServicesSmartContractDevelopmentRoute: typeof ServicesSmartContractDevelopmentRoute
  ServicesWalletDevelopmentRoute: typeof ServicesWalletDevelopmentRoute
  ServicesZkDevelopmentRoute: typeof ServicesZkDevelopmentRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServicesDaoDevelopmentRoute: ServicesDaoDevelopmentRoute,
  ServicesDefiDevelopmentRoute: ServicesDefiDevelopmentRoute,
  ServicesDefiSecurityAuditRoute: ServicesDefiSecurityAuditRoute,
  ServicesGamefiDevelopmentRoute: ServicesGamefiDevelopmentRoute,
  ServicesLaunchpadRoute: ServicesLaunchpadRoute,
  ServicesPredictionMarketDevelopmentRoute:
    ServicesPredictionMarketDevelopmentRoute,
  ServicesRwaRoute: ServicesRwaRoute,
  ServicesSmartContractDevelopmentRoute: ServicesSmartContractDevelopmentRoute,
  ServicesWalletDevelopmentRoute: ServicesWalletDevelopmentRoute,
  ServicesZkDevelopmentRoute: ServicesZkDevelopmentRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/privacy-policy",
        "/services/dao-development",
        "/services/defi-development",
        "/services/defi-security-audit",
        "/services/gamefi-development",
        "/services/launchpad",
        "/services/prediction-market-development",
        "/services/rwa",
        "/services/smart-contract-development",
        "/services/wallet-development",
        "/services/zk-development"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/privacy-policy": {
      "filePath": "privacy-policy.tsx"
    },
    "/services/dao-development": {
      "filePath": "services/dao-development.tsx"
    },
    "/services/defi-development": {
      "filePath": "services/defi-development.tsx"
    },
    "/services/defi-security-audit": {
      "filePath": "services/defi-security-audit.tsx"
    },
    "/services/gamefi-development": {
      "filePath": "services/gamefi-development.tsx"
    },
    "/services/launchpad": {
      "filePath": "services/launchpad.tsx"
    },
    "/services/prediction-market-development": {
      "filePath": "services/prediction-market-development.tsx"
    },
    "/services/rwa": {
      "filePath": "services/rwa.tsx"
    },
    "/services/smart-contract-development": {
      "filePath": "services/smart-contract-development.tsx"
    },
    "/services/wallet-development": {
      "filePath": "services/wallet-development.tsx"
    },
    "/services/zk-development": {
      "filePath": "services/zk-development.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
